micronaut:
  application:
    name: personService
  server:
    port: 8081
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/persondb
    driverClassName: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: postgres
    password: password
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
#        show_sql: true
flyway:
  datasources:
    default:
      enabled: true

rabbitmq:
  host: "localhost"
  port: 5672
  username: "user"
  password: "user"